### ISSUE TITLE
Add image for the extensions

### ISSUE THREAD

**Issue by abchatra** [jwunderl/pxt-corgio#4]
Add image to the following two extensions.

![image](https://user-images.githubusercontent.com/6107272/46220375-bfca7b80-c2fe-11e8-841d-0fc78f52c01f.png)

I believe you need to create a  icon.png  in the repo.

**Comment by abchatra** [comment]
See micorbit extensions such as https://github.com/sparkfun/pxt-weather-bit for reference

**Comment by abchatra** [comment]
@jwunderl FYI

**Comment by jwunderl** [comment]
For the versions in Microsoft/pxt-arcade/libs, correct? The variants I have (jwunderl/pxt-darts and jwunderl/pxt-corgio) have icons already with permissive licenses linked in the description that I can add if that's good.

**Comment by abchatra** [comment]
Why do we have two versions? Approved packages show the below too. 
            "jwunderl/pxt-corgio",
            "jwunderl/pxt-darts"

**Comment by jwunderl** [comment]
Peli wanted them moved into libs as they're used in the course, whereas those were added as approved packages earlier in the summer. Might as well remove those as approved packages now I suppose?

**Comment by abchatra** [comment]
Ok that makes sense. I will remove it for now. Otherwise it is bit confusing. Can you add the icons to the built-in one if they are with the right license? 

I am adding icons for animation and buttons library as well.
